### ISSUE TITLE
Homepage - Implement Initiatives section

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/calitp.org#102]
- [ ] Initiatives data collection
  - [ ] Heading
  - [ ] Content
  - [ ] (optional) Link button?
  - [ ] Recent news (filter from collection in #92)
  - [ ] Resources (hardcode links for now?)
- [ ] Border image
- [ ] Pill tabs

![image](https://user-images.githubusercontent.com/1783439/238486396-8be199ad-cec9-4aab-ac0b-08f65f38d4e0.png)

**Comment by machikoyasuda** [comment]
@segacy1 Please send us a sharp transparent PNG or SVG of this 
<img width="157" alt="image" src="https://github.com/cal-itp/calitp.org/assets/3673236/fb27b888-ebad-478e-9df3-9efb7c0c001d">

**Comment by segacy1** [comment]
@machikoyasuda adding for all three initiatives as png/svg: 
<img width="80" alt="contactless-payments" src="https://github.com/cal-itp/calitp.org/assets/33331853/930f2f31-31cb-4a76-b1ab-721642464138">
<img width="80" alt="gtfs" src="https://github.com/cal-itp/calitp.org/assets/33331853/67467313-e9d5-4767-a053-32f04ab62ee0">
<img width="80" alt="benefits" src="https://github.com/cal-itp/calitp.org/assets/33331853/1771a0e7-18e2-4e5b-a96d-1cca4fbe84d3">
![contactless-payments](https://github.com/cal-itp/calitp.org/assets/33331853/26ac8a97-3433-4b13-b791-7a71fc75da83)
![gtfs](https://github.com/cal-itp/calitp.org/assets/33331853/88458894-7b48-46ee-ab83-10c5f178f803)
![benefits](https://github.com/cal-itp/calitp.org/assets/33331853/9b01a42c-5b8e-4b3a-8e9d-090ec9579bb5)
