### ISSUE TITLE
Allow viewers to export / view printable version of press releases

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#137]

**Comment by thekaveman** [comment]
An idea to explore, using a print-specific CSS stylesheet for press releases

**Comment by machikoyasuda** [comment]
- Use to hide nav / footer, maybe make the main content column wider, show a print-only header or footer https://developer.mozilla.org/en-US/docs/Web/Guide/Printing
- What it looks like on Staging: 
<img width="1511" alt="image" src="https://github.com/cal-itp/calitp.org/assets/3673236/e9d9a2d9-7358-4f53-8288-2b78af302453">

**Comment by indexing** [comment]
@mrose914 Is this issue still relevant for the backlog?

**Comment by thekaveman** [comment]
@indexing yes, but really it should depend on first doing #234
