### ISSUE TITLE
Investigate split rectangle on Press/Resources in Mobile

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/calitp.org#174]
@segacy1 notes that in Chrome on an iPhone 12 there is a funky split between the top paragraph and the pills in the colored rectangles:

![split rectangle](https://user-images.githubusercontent.com/33331853/244730550-4d9c0a87-6f7b-4f6c-98fe-e4e7a30c223c.jpeg)

@thekaveman was unable to reproduce in Chrome/Firefox responsive view at 320px and higher.

**Comment by machikoyasuda** [comment]
Note: This bug is for the Rhombus on Safari entirely, both Desktop and Mobile.

Just to be sure, @thekaveman @angela-tran does the site look okay on Mobile on Android/Chrome mobile browser (and any other mobile browsers y'all use on Android?) 

I'm investigating + working on this today.
