### ISSUE TITLE
Update content within Initiatives section to better frame outbound link to MobiMart

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#208]
Feedback from Marty at CalSTA was to better frame MobiMart within the context of our initiatives

Requirements: 
- Add line above button to contextualize what MobiMart is and how it connects to the initiative: "For more information about the products available to support this initiative, please visit the California Mobility Marketplace."
- Hide MobiMart button for Benefits and GTFS since we don't have products on MobiMart for Benefits or GTFS (We will add the button back for GTFS-RT when it is available towards the Fall)

**Comment by machikoyasuda** [comment]
This is a blocker to launch.
