### ISSUE TITLE
[POST-LAUNCH] Redirect QR Code to new calitp.org from microsite

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#210]
Currently, we have a calitp QR code printed on stickers that points to a bitly microsite. Once the calitp.org redesign is live, we should point that QR code to the new site.

**Comment by thekaveman** [comment]
Currently the QR code points to `calitp.org/links`, which does the redirect to the bitly site.

So we'll just need to update our own redirect from `/links` to go to the homepage.
