### ISSUE TITLE
Release Notes for calitp.org launch

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#214]
Provide short list of bullets summarizing the changes and include slides.

**Comment by machikoyasuda** [comment]
## Major technical changes
- Upgrades Bootstrap from 5.0 to 5.2.3.
- Adds Dependabot for Bundler dependencies
- Adds CODEOWNERS file

**Comment by machikoyasuda** [comment]
done https://github.com/cal-itp/calitp.org/releases/tag/2023.08.1
