### ISSUE TITLE
Route Fifty article now 404s - follow up with webmaster

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#228]
We link to https://www.route-fifty.com/digital-government/2023/01/caltrans-serves-dashboard-metrics-local-transit-agencies/381473/, which is 404ing. 

Emailed their webmaster (webmaster@routefifty.com) at 6:30p on 8/3.

**Comment by thekaveman** [comment]
@mrose914 I think it is back up!

**Comment by esquared415** [comment]
Happy to report that the Route 50 link / article is now live again:
https://www.route-fifty.com/digital-government/2023/01/caltrans-serves-dashboard-metrics-local-transit-agencies/381473/

So this ticket can be closed without any action.

CC: @mrose914

**Comment by esquared415** [comment]
Article / link works again. So please do not delete from our website.
