### ISSUE TITLE
Refactor all Cal-ITP Press Release PDFs to use Press Release template

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/calitp.org#234]
Will require some editorial assistance from @esquared415

**Comment by machikoyasuda** [comment]
There are actually only 2 Cal-ITP press releases that need to be converted:

1. https://www.calitp.org/assets/Contactless.Payments.MSA.pdf (This one has no date on the PDF itself. Does anyone have a date for this?)
2. https://www.calitp.org/assets/Cal-ITP.FirstNet.PressRelease.221103.pdf (Has a data table that will be need to be converted to HTML).

Need to make sure any links to these press releases are updated. The first date-less PDF is linked on other press releases: https://github.com/search?q=repo%3Acal-itp%2Fcalitp.org%20Contactless.Payments.MSA.pdf&type=code

Should the PDFs remain, while the main canonical press release link is changed to the HTML one?

Should this press releases that are not hosted on calitp.org also be converted?
1. ValleyCAN joint press release https://valleycan.org/wp-content/uploads/2022/08/ValleyCAN_PR_080122_Final.pdf

Questions for @thekaveman @mrose914

**Comment by thekaveman** [comment]
> Should the PDFs remain, while the main canonical press release link is changed to the HTML one?

>> I believe @thekaveman suggested that we keep the PDFs so as not to disrupt any materials with these links we may not know about, which makes sense to me.

Yep this all sounds right!

**Comment by machikoyasuda** [comment]
@mrose914 the ValleyCAN one is also from our website. 

<img width="1512" alt="image" src="https://github.com/cal-itp/calitp.org/assets/3673236/ce6eb0df-2eb8-4ecb-ab8c-ea1cec60d8ee">


And the content was pulled from the spreadsheet: 
https://docs.google.com/spreadsheets/d/1xJpgr8JBG9TgZF2mHB8Vjnhu453No4dHoNjFIhb0FQw/edit#gid=0

<img width="1512" alt="image" src="https://github.com/cal-itp/calitp.org/assets/3673236/ea8f2e43-770a-413d-9f1e-fee2b248a133">
