### ISSUE TITLE
Increase spacing between links within initiatives section to 16px

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#236]
Currently the spacing between links within each of the Initiatives on the homepage of calitp.org is a little hard to read. Request from the team is to double (from 8px > 16px) the spacing to provide more space between articles/docs. 

cc @segacy1 @esquared415

**Comment by machikoyasuda** [comment]
@mrose914 @segacy1 I also just noticed there's a bug in the way the Initiatives section is pulling links. The design on Figma indicates that there should be a maximum of 3 links per section, but currently, the app is loading _all_ applicable links. Reducing the number of links in that section down to 3 will also improve overall readability. I think we should make a bug for this ticket, give it an estimate of 5 for a fix and a label of `Stretch`. It's a bit more complex to fix, so don't think it can be done in this cycle.
