### ISSUE TITLE
Add new field to issue templates to verify content has been proofed/approved 

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#242]
As part of our request process to get content onto calitp.org, we should ensure there is a way to verify the content is approved for posting. 

We should add a field to the issue templates we have for Press Releases and Resources that asks:

Has your content (document and headline) been approved by @esquared415?  Yes/No _(If No, please allow 3-5 business days for review by Erika)._

**Comment by thekaveman** [comment]
@indexing @mrose914 this is a super small task, I can get it done today.
