### ISSUE TITLE
2 minor copy updates to initiatives section on Cal-ITP.org

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#258]
1. **On the homepage, within the Enabling Contactless Payments Rhombus, please replace existing copy with modified version below:** 

Riding transit should be as easy as buying a cup of coffee! Adding a contactless payment reader to a bus or train means customers can quickly and easily tap to pay as they board with the debit or credit card or smartphone that’s already in their pocket—just like they’d tap to buy a coffee.

Cal-ITP is making it easier for public transit providers to purchase the key hardware and software needed to accept contactless payments through statewide contracts established by the California Department of General Services (DGS). In addition, the Cal-ITP team provides resource materials and technical assistance throughout the process.

For more information about the products available to support this initiative, please visit the
[California Mobility Marketplace](https://www.camobilitymarketplace.org/).

2.  **On the homepage, within the GTFS Rhombus, please replace existing copy with modified version below:** 

Cal-ITP is helping transit providers remove the guesswork for riders wondering when the next bus or train will arrive or if they’ll make their connection by using the General Transit Feed Specification (GTFS)—the global standard for publishing transit information. Cal-ITP developed [California Transit Data Guidelines](https://dot.ca.gov/cal-itp/california-transit-data-guidelines) and is working to ensure statewide GTFS schedule/static coverage and GTFS Realtime. The Cal-ITP team will support transit providers by assessing their systems and providing technical assistance so riders can easily access complete, accurate, consistent, and timely mobility data for their journey.

**Comment by esquared415** [comment]
@mrose914 Thank you for flagging me to these queries!

1. Enabling Contactless Payments Rhombus: Updated copy is Approved.
2. GTFS: Yes, please change "[California Minimum GTFS Guidelines](https://dot.ca.gov/cal-itp/california-minimum-general-transit-feed-specification-gtfs-guidelines)" to:
California Transit Data Guidelines
and hyperlink that text to:
https://dot.ca.gov/cal-itp/california-transit-data-guidelines

(I could have sworn there was a ticket for #2 a while back. Thank you for catching @lmshoup1!)
