### ISSUE TITLE
Replace Resources on calitp.org with refreshed versions for improved accessibility

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#269]
I have uploaded a folder [here](https://drive.google.com/drive/folders/1ZcWc_PIKt9rCO5aZ-Zyswfkw9r4DKmMl?usp=sharing) with updated versions of the resources currently hosted on calitp.org/resources. 

We would like to replace the existing resources with the refreshed versions which contain a number of accessibility improvements, mostly the addition of tags and cleanup of logo tags.

**Comment by machikoyasuda** [comment]
- Move these PDFs to the /assets/ folder
