### ISSUE TITLE
New resource: Cal-ITP / CARB Market Sounding: Mobility Rewards Strategy & Demonstration Project

### ISSUE THREAD

**Issue by pbrebel** [cal-itp/calitp.org#270]
### Approved?

No

### Title

Cal-ITP / CARB Market Sounding: Mobility Rewards Strategy & Demonstration Project

### Asset URL

https://docs.google.com/document/d/1Mg_6NcY-b4xrJaj2iP9Ku_IYfDeujdqH/edit#heading=h.gjdgxs

### Category

Case studies

### Tag

Benefits

### Date - Year

2023

### Date - Month

11

**Comment by pbrebel** [comment]
Hi team and thank you for working on this! Please note that the report has been checked by Lev (for grammar and editing purposes) and approved by Gillian (for authorisation to use her name in the opening letter). Please also note that we are expecting approval for the Terms & Conditions part from CARB's legal team, before we can make this document public tomorrow.

**Comment by thekaveman** [comment]
@mrose914 can you please try uploading the PDF again, I think it didn't attach to your last comment?
