### ISSUE TITLE
Create guidance for Cal-ITP on file naming for the web

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/calitp.org#275]
This mostly applies to PDF resources created for hosting on this site.

- [ ] Prefix filenames with `Cal-ITP`
- [ ] Avoid spaces between words, use dash `-` or dot `.` to separate words instead
- [ ] Avoid using characters besides: letters, numbers, dash, dot, and underscore `_`
- [ ] Avoid using revision dates in filenames, limit usage of revision numbers unless commonly understood and expected by audience
  - Avoid: `report-june-2024.pdf`, `file-v1.3.pdf` (random files with versions devoid of context)
  - OK: `GTFS-guidelines-v3.pdf` (v3 of the GTFS Guidelines, a well-know and ever-evolving document)
- [ ] Shorter is better

**Comment by machikoyasuda** [comment]
Suggestion: Add each of these as a checklist question to the issue template for resources - https://github.com/cal-itp/calitp.org/blob/main/.github/ISSUE_TEMPLATE/new_resource.yml

Example:

- [ ] Did you start the filename with `Cal-ITP`?
- [ ] There are no spaces between words in the filename.
- [ ] There are no revision dates in the filename, unless commonly understood and expected by the audience.
- [ ] The only characters in the filename are: letters, numbers, `-`, `.` and `_`.
