### ISSUE TITLE
BankOn resource request

### ISSUE THREAD

**Issue by AngellyTovar** [cal-itp/calitp.org#276]
### Approved?

Yes

### Title

Fact Sheet: Enhancing the transit experience with BankOn accounts

### Asset URL

https://drive.google.com/file/d/1yibJFxrNInOleQEpx3GgTwB-dE_R0jZh/view?usp=drive_link

### Category

Fact sheets & overviews

### Tag

Contactless payments

### Date - Year

2023

### Date - Month

10

**Comment by thekaveman** [comment]
This one can be a simple HTML-based resource page.

**Comment by AngellyTovar** [comment]
An HTML would be great! I included a PDF resource as it's easy to upload to the drive and share the link here, no real preference though.

**Comment by thekaveman** [comment]
@AngellyTovar thanks! This was a note for whoever works on this ticket -- you followed the process exactly right! :+1:
