### ISSUE TITLE
New resource request: ODS one pager

### ISSUE THREAD

**Issue by o-ram** [cal-itp/calitp.org#300]
### Approved?

Yes

### Title

Overview: Operational Data Standard

### Is the document correctly named and formatted?

- [X] Did you start the filename with `Cal-ITP`?
- [X] Did you remove all spaces between words in the filename? The only acceptable characters in the filename are letters, numbers, `-`, `.` and `_`.
- [X] Did you ensure there are no revision dates or numbers in the filename? Limit usage of revision numbers or dates unless commonly understood and expected by the audience. Avoid `report-june-2024.pdf`, `file-v1.2.pdf`. Allowed `GTFS-guidlines-v3.pdf`, as version 3 is an official version number.
- [X] Did you run this PDF through Adobe Acrobat's Accessibility Checker, and ensure the PDF passes all accessibility checks?

### Asset URL

https://drive.google.com/file/d/1U8DKyqj9Nx5J0rpgVlHMBsctEm0I6IIO/view?usp=sharing

### Category

Fact sheets & overviews

### Tag

GTFS

### Date - Year

2023

### Date - Month

11

**Comment by o-ram** [comment]
@mrose914 this is another one pager we took to conferences. I had a harder time with this one making it through the accessibility checker, so I left both items marked as "needs manual check" alone, but happy to do whatever is needed. Here's the report it generated: 
[Cal-ITP_ODS_One_pager.pdf.accreport 2.html.zip](https://github.com/cal-itp/calitp.org/files/14146432/Cal-ITP_ODS_One_pager.pdf.accreport.2.html.zip)

**Comment by thekaveman** [comment]
@mrose914 can you please do the manual review of this PDF for accessibility concerns and reply in this ticket when you have confirmed it is good to go?

**Comment by thekaveman** [comment]
I believe Segacy had done extensive checking and reworking of the Cal-ITP color schemes (for the websites at least) to be accessibility compliant before she went out. 

cc @srhhnry @machikoyasuda

**Comment by srhhnry** [comment]
I just took a look at the one-pager and tested with the Figma tool we use (Stark). Everything passes to AAA WCAG standards (the highest accessibility standard for web text) **except** for the blue subheading (e.g. Reduce cost and improve efficiency) which is hex code 046B99. I believe we updated that color (also known at Cal-ITP blue) to 045B86. So it looks like Segacy might have just been using the out of date color. I can change that in the Figma file now if that's preferable, but will need some guidance on creating PDFs

**Comment by srhhnry** [comment]
Subheaders are updated to the new Cal-ITP blue. I also noticed there is a light grey page 1 at the bottom that also does not pass accessibility tests. I can see why it's light (to detract emphasis) but should I increase the contrast on that as well? I would argue we don't need it if there's...only one page.

**Comment by srhhnry** [comment]
Page number removed

**Comment by srhhnry** [comment]
Export can be found here on Figma: https://www.figma.com/file/XiYsM66X6c3nzVikVYB3or/ODS-one-pager?type=design&node-id=0%3A1&mode=design&t=wxObPYDk5d8YZutV-1

or attached here
[ODS one-pager.pdf](https://github.com/cal-itp/calitp.org/files/14197193/ODS.one-pager.pdf)
