### ISSUE TITLE
Update calitp.org resource form with comms + accessibility tweaks

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#307]
Request to make two updates to the [Resource Request form](https://github.com/cal-itp/calitp.org/issues/new?assignees=&labels=content%2Cresources&projects=&template=new_resource.yml&title=New+resource+request)

- [ ] **UPDATE APPROVAL SECTION**

Approved?
Has your content (document and headline) been approved for publication? If not, please confirm approval in #comms-and-content.

- [ ] **UPDATE ACCESSIBILITY CHECK**

Did you run this PDF through Adobe Acrobat's Accessibility Checker, and ensure the PDF passes all accessibility checks? NOTE: Please review [this doc](https://docs.google.com/document/d/1CkXfHDuJ4fR2wikGrsgyt4Dib6YdY3AhFmYtsk4kQXg/edit#heading=h.ecbzu7qezn59) to get more information on accessibility and how to run accessibility checks.*

**Comment by thekaveman** [comment]
@machikoyasuda this feels pretty straightforward, think you can take of this week?

**Comment by machikoyasuda** [comment]
Marissa read my mind! I was going to suggest this.
