### ISSUE TITLE
Cal-ITP Satellite Report 

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#337]
### Approved?

Yes

### Is the document correctly named and formatted?

- [X] Did you start the filename with `Cal-ITP`?
- [X] Did you remove all spaces between words in the filename? The only acceptable characters in the filename are letters, numbers, `-`, `.` and `_`.
- [X] Did you ensure there are no revision dates or numbers in the filename? Limit usage of revision numbers or dates unless commonly understood and expected by the audience. Avoid `report-june-2024.pdf`, `file-v1.2.pdf`. Allowed `GTFS-guidlines-v3.pdf`, as version 3 is an official version number.
- [X] Did you run this PDF through Adobe Acrobat's Accessibility Checker, and ensure the PDF passes all accessibility checks? Please review [this checklist](https://docs.google.com/document/d/1CkXfHDuJ4fR2wikGrsgyt4Dib6YdY3AhFmYtsk4kQXg/edit#heading=h.ecbzu7qezn59) to get more information on accessibility and how to run accessibility checks.

### Date - Year

2024

### Date - Month

05

### Title

Cal-ITP Satellite Report 

### Asset URL

https://drive.google.com/file/d/1Xu1zmipzP7BUskriYLtqcZICgrLCgRVx/view?usp=drive_link

### Category

Case studies

### Tag

Contactless payments

**Comment by thekaveman** [comment]
@mrose914 no problem - I just requested access to the doc

**Comment by thekaveman** [comment]
@mrose914 do we want to update the document title? This is a little funky:

![image](https://github.com/cal-itp/calitp.org/assets/1783439/0a9c9883-d93a-4461-a900-38ecdf733bee)

**Comment by thekaveman** [comment]
@mrose914 it's weird -- it looks fine when I view it in the browser, but as soon as I download and view in a PDF viewer I still see that weird `Accessibility uppdate...` title :thinking:

**Comment by thekaveman** [comment]
@mrose914 Yes it looks good now!! :clap: 

![image](https://github.com/cal-itp/calitp.org/assets/1783439/8a154208-513b-49ee-a2f4-72a1665fdcef)
