### ISSUE TITLE
Report on Transit Technology Ecosystem

### ISSUE THREAD

**Issue by aliatt2** [cal-itp/calitp.org#341]
### Approved?

Yes

### Is the document correctly named and formatted?

- [X] Did you start the filename with `Cal-ITP`?
- [X] Did you remove all spaces between words in the filename? The only acceptable characters in the filename are letters, numbers, `-`, `.` and `_`.
- [X] Did you ensure there are no revision dates or numbers in the filename? Limit usage of revision numbers or dates unless commonly understood and expected by the audience. Avoid `report-june-2024.pdf`, `file-v1.2.pdf`. Allowed `GTFS-guidlines-v3.pdf`, as version 3 is an official version number.
- [X] Did you run this PDF through Adobe Acrobat's Accessibility Checker, and ensure the PDF passes all accessibility checks? Please review [this checklist](https://docs.google.com/document/d/1CkXfHDuJ4fR2wikGrsgyt4Dib6YdY3AhFmYtsk4kQXg/edit#heading=h.ecbzu7qezn59) to get more information on accessibility and how to run accessibility checks.

### Date - Year

2024

### Date - Month

05

### Title

Caltrans Report on Transit Technology Ecosystem

### Asset URL

https://drive.google.com/file/d/1r7kQqIwCA-bS2uLVzjOVW2JbfWCd_DpC/view?usp=sharing

### Category

Case studies

### Tag

Contactless payments, GTFS

**Comment by aliatt2** [comment]
Updated and remediated document! 
[caltrans-tddc-task-1-report -final-axcheck-a11y.pdf](https://github.com/user-attachments/files/15506813/caltrans-tddc-task-1-report.-final-axcheck-a11y.pdf)

**Comment by mlgilbert18** [comment]
Abbreviated version of the remediated doc is here! This will be the one we will push on social media/newsletter.

[caltrans-tddc-task-1-report -final-short.pdf](https://github.com/user-attachments/files/15744070/caltrans-tddc-task-1-report.-final-short.pdf)
