### ISSUE TITLE
[TRACKING] Amplitude tracking for calitp.org

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#349]
I'd like to implement basic tracking for some of the new content on calitp.org, spreadsheet in progress: https://docs.google.com/spreadsheets/d/1kHrvfI0pa3NFvLa63JvM1zl9gyxJET5Bxn9sxoHEj6c/edit?gid=1092221564#gid=1092221564

Will discuss 7/9 when we break down tickets.

cc @thekaveman

**Comment by machikoyasuda** [comment]
@mrose914 Can you create a dev ticket? I think this dev ticket should be worked on _after_ the final staging link PR is created.

**Comment by ohmegasquared** [comment]
@thekaveman - can we close this if its covered under google analytics?
