### ISSUE TITLE
Implement basic Amplitude tracking for calitp.org 

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#385]
In order to build out very basic funnels, we would like to track a number of events on calitp.org. Now that we have more pages (Partners and Customer Stories) with more CTAs, potential flows, and different groups of interested stakeholders, it would be helpful to be able to answer simple questions such as: 

- How many site visitors went from viewing Customer Stories > clicking to send an email to hello@calitp.org?
- How many site visitors went from the homepage > Customer Stories?
- How many site visitors went from the homepage > view our Sources? 
Etc 

While we do have some basic capabilities in Google Analytics, the ability to build out simple, event-based funnels is not as clear (perhaps I need a tutorial).

Spreadsheet with the events to track (which is a subset of all possible events) is here: https://docs.google.com/spreadsheets/d/1kHrvfI0pa3NFvLa63JvM1zl9gyxJET5Bxn9sxoHEj6c/edit?gid=1092221564#gid=1092221564

**Comment by indexing** [comment]
We have Google Analytics which is sufficient for calitp.org.
