### ISSUE TITLE
Broken image: Benefits press release has broken image

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/calitp.org#390]
Benefits press release has broken image and a broken link to the image:

https://www.calitp.org/press/cal-itp-benefits-launch

<img width="1509" alt="image" src="https://github.com/user-attachments/assets/97953eeb-4e99-49ab-9cda-a503ef7acb74">

https://docs.calitp.org/benefits/use-cases/img/senior-success.gif

**Comment by machikoyasuda** [comment]
@indexing fyi

**Comment by indexing** [comment]
We can replace it with the walkthrough posted on YouTube. https://youtu.be/vAJ_3lTeWJU?si=4YhOczT5VvglhRIF

Looks like changing source will require some slight copy changes for context.
