### ISSUE TITLE
Replace PDFs with accessibility-refreshed versions

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#399]
There are two PDFs that have been refreshed for accessibility (mostly re-formatting logos). Links to the finalized docs below: 

Fact Sheet: Prepaid Card Recommendations - https://drive.google.com/file/d/1pHrA5jKdoPwZdJAFRKrfsDphu7GBDXOD/view?usp=drive_link

Overview: How Cal-ITP incorporated public feedback into CA Transit Data Guidelines v3.0 - https://drive.google.com/file/d/1T6JD67sW7Hsv5iwwQCwj80B_UPiojE3i/view?usp=drive_link

Note: No need to update the dates, these are not materially different in content they are just slightly re-formatted.

**Comment by allejo** [comment]
Will handle it tomorrow. I just need access to those Google Drive links

**Comment by thekaveman** [comment]
@mrose914 it looks like those files are both private.
