### ISSUE TITLE
New resource request: Cal-ITP 2023 Holiday Service Transit Traveler Information Research

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/calitp.org#407]
### Approved?

Yes

### Is the document correctly named and formatted?

- [X] Did you start the filename with `Cal-ITP`?
- [X] Did you remove all spaces between words in the filename? The only acceptable characters in the filename are letters, numbers, `-`, `.` and `_`.
- [X] Did you ensure there are no revision dates or numbers in the filename? Limit usage of revision numbers or dates unless commonly understood and expected by the audience. Avoid `report-june-2024.pdf`, `file-v1.2.pdf`. Allowed `GTFS-guidlines-v3.pdf`, as version 3 is an official version number.
- [X] Did you run this PDF through Adobe Acrobat's Accessibility Checker, and ensure the PDF passes all accessibility checks? Please review [this checklist](https://docs.google.com/document/d/1CkXfHDuJ4fR2wikGrsgyt4Dib6YdY3AhFmYtsk4kQXg/edit#heading=h.ecbzu7qezn59) to get more information on accessibility and how to run accessibility checks.

### Date - Year

2024

### Date - Month

10

### Title

Cal-ITP 2023 Holiday Service Transit Traveler Information Research

### Asset URL

https://drive.google.com/file/d/116wGfNNYhaTGJr7LR2M0JTmQ_OYf9YrC/view?usp=drive_link

### Category

Case studies

### Tag

GTFS

**Comment by thekaveman** [comment]
Thanks for submitting this ticket @evansiroky! I have added it to our coming Sprint, starting next week on Oct 9.

**Comment by evansiroky** [comment]
@thekaveman, @machikoyasuda any updates on this?

**Comment by machikoyasuda** [comment]
@evansiroky In review now https://github.com/cal-itp/calitp.org/pull/409
