### ISSUE TITLE
headings cut off at certain window widths

### ISSUE THREAD

**Issue by afeld** [cal-itp/calitp.org#69]
<img width="1047" alt="Screenshot 2022-12-06 at 12 44 23 PM" src="https://user-images.githubusercontent.com/86842/206006584-bac98be8-f37d-4cb1-acca-418c96c57637.png">

Seen on Firefox v107.0.1.

**Comment by machikoyasuda** [comment]
Confirmed that this is not an issue on Safari and Chrome.

**Comment by thekaveman** [comment]
Closing as we are implementing a new design for the homepage which will obviate this issue.
