### ISSUE TITLE
Implement new calitp.org redesign

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#80]
High level requirements: 

- Shortens context about the program 
- Adds scrollable initiatives view 
- Adds Resources page 
- Adds Press page 
- Improves navigation to relevant content (for bitly site replacement)

Designs in progress here: https://www.figma.com/file/TfWk1iDHdlt7bSA3DjQuQv/Mobility-Marketplace?node-id=5299-23559&t=0sznFMu9eKaRxejn-0

**Comment by thekaveman** [comment]
Remove assignment while blocked.

**Comment by machikoyasuda** [comment]
Content approved by @esquared415 on April 30, 2023

Here: https://docs.google.com/document/d/1uLjCTC0LEjaDtOivWQp0OFM0ZVIjULnr_cZ6-QgAi0k/edit#heading=h.6xss7cceyx3k

**Comment by segacy1** [comment]
Hi! I also wanted to flag matching the styles here to what's in mobimart (which is the current design). @mrose914 @angela-tran not sure if that's something that requires its own ticket or should be included in the description here!

**Comment by thekaveman** [comment]
Reopening so we can close with the final PR from `staging` --> `main`
