### ISSUE TITLE
File resource audit on calitp.org

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#81]
Now that are going to add dedicated Press and Resources pages to the calitp.org site, we should audit the current content and make sure we are not above the limit for hosting on Github (1GB).

Todos: 
- Audit to determine total space remaining 
- Make recommendations, if applicable, about optimizing size/storage 
- Cross reference existing docs with not yet added docs (Marissa TODO using https://docs.google.com/spreadsheets/d/1xJpgr8JBG9TgZF2mHB8Vjnhu453No4dHoNjFIhb0FQw/edit#gid=0)

**Comment by angela-tran** [comment]
On my computer I see:
The total size of the repo is ~34 MB (includes `.git` folder)
The `src/assets` folder (containing all the PDFs) is ~15 MB
`src/images` is at 352 KB

So we're not at risk of hitting the limit yet. Still a good idea to eventually migrate to a better file-hosting approach.

**Comment by thekaveman** [comment]
Thank you for that overview @angela-tran. I am going to close this now in favor of the discussion on #82.

As we can see, the storage size won't really be a concern for some time. But rather managing an increasing number of PDF files (and ongoing updates to those files) becomes less and less scalable and stable over time.
