### ISSUE TITLE
Document requirements for filtering on Press and Resources pages

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#83]
Confirm the possible interactions for the filtering at the top of the Press and Resources pages.

**Comment by thekaveman** [comment]
Closing this in favor of #90, please add any updates there. [In Slack, @segacy1 confirmed the pills should be multi-select](https://cal-itp.slack.com/archives/C018XMWT2FN/p1683216813798279?thread_ts=1683216205.313849&cid=C018XMWT2FN).
