### ISSUE TITLE
Finalize copy and content for calitp.org

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#84]
See doc here with content: https://docs.google.com/document/d/1uLjCTC0LEjaDtOivWQp0OFM0ZVIjULnr_cZ6-QgAi0k/edit#heading=h.6xss7cceyx3k

TODO: Review with @esquared415

**Comment by machikoyasuda** [comment]
This is finalized right @mrose914? So this ticket can be closed, I believe.

**Comment by machikoyasuda** [comment]
@mrose914 Has copy been approved by @esquared415? Can this ticket be closed?
