### ISSUE TITLE
Implement changes for homepage (ordering and copy)

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/calitp.org#89]
In the new design of calitp.org, the homepage has been shortened and reordered. This ticket involves implementing all that's on the homepage design, _except_ the navbar and footer which will be done in a separate ticket. 

The biggest feature to implement is the scrollable "initiatives" view since we don't have anything like that on the site right now.

Content: https://docs.google.com/document/d/1uLjCTC0LEjaDtOivWQp0OFM0ZVIjULnr_cZ6-QgAi0k/edit#heading=h.6xss7cceyx3k

Designs in Figma: https://www.figma.com/file/TfWk1iDHdlt7bSA3DjQuQv/Mobility-Marketplace?type=design&node-id=5305-26803&t=qvrYiPrTQX0GD3Vm-4

<details><summary>Screenshots</summary>

| Desktop | Mobile |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/25497886/236338476-a90d0d31-a723-4262-8c1f-0cd59a517263.png) | ![image](https://user-images.githubusercontent.com/25497886/236338577-ed68e1c1-8ebf-4d20-adab-0066be5ee15f.png) |

</details>

## Tasks

To be broken out into individual issues

- [ ] #100
- [ ] #101
- [ ] #102
- [ ] #103

**Comment by thekaveman** [comment]
Closing this in favor of the more specific tickets above.
