### ISSUE TITLE
Figure out implementation for filtering

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/calitp.org#90]
This task is to figure out a clean implementation for the "filtering pills" shown on designs for the new "Press" and "Resource" pages.

Some questions to answer are:
 - Do we want to do this with a CSS-only approach? Do we need Javascript?
 - How should the data (links to press releases and resources) be modeled to support the filtering implementation?

@segacy1 confirmed in Slack that the user should be able to select multiple pills.

The result of this task is not a pull request that gets merged in, but rather a clear pattern for implementers of the "Press" and "Resource" pages to follow.

![image](https://user-images.githubusercontent.com/25497886/236339463-392d1058-bc37-4baf-9496-b42fc7ded77b.png)

**Comment by angela-tran** [comment]
Tagging #83 as related

**Comment by thekaveman** [comment]
> [Navs and tabs · Bootstrap v5.3](https://getbootstrap.com/docs/5.3/components/navs-tabs/#pills-with-dropdowns) + https://getbootstrap.com/docs/5.3/components/navs-tabs/#javascript-behavior  like the Contact Us page on mobimart.

**Comment by thekaveman** [comment]
[UX conversation on Slack](https://cal-itp.slack.com/archives/C018XMWT2FN/p1684180778079749)

**Comment by thekaveman** [comment]
## UX Summary

- Each pill is either `on` or `off`
- Only one pill can be `on` at one time
- Turning one pill `on` turns all others `off`
- Turning one pill `on` filters the list to items matching that pill
- Turning a pill `off` removes its filter
- The pill background is filled for a pill that is `on`
- The pill background is transparent for a pill that is `off`

**Comment by angela-tran** [comment]
This is what I had gotten working before the Compiler retreat week:

![calitp-filtering](https://github.com/cal-itp/calitp.org/assets/25497886/4dfaa3fe-aed7-43b2-89c5-f5995cb47531)

This uses some of the WIP code from https://github.com/cal-itp/calitp.org/pull/142 to style the pills. I wrote some Javascript to implement turning a pill `off` since that is not provided by Bootstrap. I'll push the WIP code soon.

I think this meets all the items listed in the comment above under "Summary".

**Comment by angela-tran** [comment]
In the Slack convo about the UX, we said that when the page loads, all pills are off. What I gather from the Slack thread is that the user sees an unfiltered list of all articles when all pills are off. I have some idea of the Javascript needed to accomplish this and will work on it today

**Comment by angela-tran** [comment]
On 5/31, @machikoyasuda and I tested the UX of the filters on the preview site.

Found a bug with keyboard interaction (deselect not working for keyboard edge case):
 - tab to filters
 - select one using Enter
 - deselect using Enter
 - use arrow to navigate to next filter
    - "all" tab is still showing

Another bug(?) / unexpected behavior (have to hit Enter twice to deselect):
 - tab to filters
 - select one using Enter
 - use arrow to navigate to next filter
 - try to deselect using Enter
    - filter is still selected, have to hit Enter again to actually deselect

I was working on implementing an event listener to fix the first one and now am working on removing redundant code. Was also still looking into the second bug.

**Comment by machikoyasuda** [comment]
This issue was closed by @angela-tran's pr here https://github.com/cal-itp/calitp.org/pull/164
