### ISSUE TITLE
Implement Resources feature

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/calitp.org#91]
Depends on #90 for the filtering part

The styling and content for this page can be worked on independently from the filtering part.

Figma design: https://www.figma.com/file/TfWk1iDHdlt7bSA3DjQuQv/Mobility-Marketplace?type=design&node-id=5305-30392&t=qvrYiPrTQX0GD3Vm-4

## Tasks

- [x] #104
- [x] #105
- [ ] Filters from #90
- [x] ~"Show More" link~ Leaving this until the next Sprint

**Comment by angela-tran** [comment]
@mrose914 just a heads up that we will need the actual list of Resources (and their links) to put on this page

**Comment by thekaveman** [comment]
Thank you @mrose914 those edits are helpful! 

One last question: the Figma designs show a date next to each resource, but what the date should be is not obvious for each of them. Can you please help getting a date assigned to each row in the sheet?

(This is more obvious for the existing press so you can ignore those).

**Comment by thekaveman** [comment]
@mrose914 one last question for you here:

The Categories in the spreadsheet include:

- Case Study
- Fact Sheets
- Slide Decks
- One-Pager

Should these correspond exactly to the section headings on the landing page?

E.g. in the following screenshot the section headings are:

- Case Studies
- Fact Sheets & Overviews
- Testimonials (I know we aren't using this one right now)

![image](https://github.com/cal-itp/calitp.org/assets/1783439/dca1d9bd-2f2a-47f5-b55a-39bf77c1c6fe)

Based on the what is in the sheet, do these categories make sense (all pluralized nouns)?  Should any of these be grouped together (like Fact Sheets & Overviews in the screenshot)?

- Case Studies
- Fact Sheets
- Slide Decks
- One-Pagers
