### ISSUE TITLE
Redirect to canonical domain

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/calitp.org#94]
With the changes coming in #80, it may be time to rethink how we redirect the additional vanity URLs that we maintain:

| Domain | Current | Suggestion | Status |
| --------- | -------- | ------------ | ------- |
| `calitp.org` | canonical | Leave as-is |  |
| `cal-itp.com` | redirects to https://dot.ca.gov/cal-itp | Update redirect to canonical | ✅ Done |
| `cal-itp.net` | redirects to https://dot.ca.gov/cal-itp | Update redirect to canonical | ⚪ Todo  |
| `cal-itp.org` | redirects to https://dot.ca.gov/cal-itp | Update redirect to canonical | ✅ Done |

The page at https://dot.ca.gov/cal-itp hasn't seen an update since February 2021, lists old contact information, and generally should not be prioritized in terms of relevant Cal-ITP content.

@mrose914 giving you the initial assignment as I think we need to confirm with Caltrans/CalSTA that this is OK.

**Comment by esquared415** [comment]
@mrose914 I think Marty is the right person to start with, at least. And I think that a slide explainer would be great (and would love to see it mention what happens when someone Googles "calitp"). Thanks!

**Comment by thekaveman** [comment]
@mrose914 just confirming, are we good to make these changes?

**Comment by thekaveman** [comment]
@angela-tran @machikoyasuda I did this for the first of three redirects, and wrote up some steps above for how to do it for the other two.

Maybe each of you can take one to get practice with DNS.

**Comment by angela-tran** [comment]
@machikoyasuda I'll take `cal-itp.org`

**Comment by angela-tran** [comment]
@thekaveman I'm at Step 5 from your instructions where I need to add a URL redirect to **Bulk Redirects**. I'm running into an issue where when I click "Save", it sends me to the "Edit URL redirects" page and shows me an "Authentication error" message.

![image](https://github.com/cal-itp/calitp.org/assets/25497886/5e06a5b4-535c-41a2-9d88-11e41a9fa8e4)

![image](https://github.com/cal-itp/calitp.org/assets/25497886/776a7dc0-4b43-4aa0-aa66-c00c1f05d535)

**Comment by angela-tran** [comment]
I got through all the other steps successfully - [`cal-itp.org`](https://cal-itp.org) and [`www.cal-itp.org`](https://www.cal-itp.org) redirect to `calitp.org`

**Comment by thekaveman** [comment]
@angela-tran updated your permissions in Cloudflare, try again?

**Comment by angela-tran** [comment]
> @angela-tran updated your permissions in Cloudflare, try again?

It works now! I was able to add my URL. 

Should we check "Include subdomains" and "Subpath matching"? Maybe that would make `cal-itp.org/resources` redirect to `calitp.org/resources`?

![image](https://github.com/cal-itp/calitp.org/assets/25497886/953d6c6e-86d0-45fe-af84-84e3e0f40f98)

From Cloudflare guide:
> 3. Use [Bulk redirects](https://developers.cloudflare.com/rules/url-forwarding/bulk-redirects/) to forward traffic from your alias domain to your other domain. Select _Include subdomains_ and _Subpath matching_ to cover your entire alias domain (for example, www.previous.com and www.previous.com/examples).

**Comment by thekaveman** [comment]
Sounds good.

Although I'm not sure why this was working _before_ you added the entry to that redirect map? It seems like the redirect was already in place? https://github.com/cal-itp/calitp.org/issues/94#issuecomment-1670351937

**Comment by angela-tran** [comment]
> Sounds good.

Ok nvm, we do not want to check _Include subdomains_ and _Subpath matching_. When I checked those, `cal-itp.org/resources` redirected me to `calitp.org`. 😳 I went back to having them unchecked, and now `cal-itp.org/resources` just goes to that page, doesn't redirect anywhere.

> Although I'm not sure why this was working _before_ you added the entry to that redirect map? It seems like the redirect was already in place? [#94 (comment)](https://github.com/cal-itp/calitp.org/issues/94#issuecomment-1670351937)

Hmm, yeah. Once I added the production domain in Netlify it worked without needing any Bulk Redirect.

**Comment by thekaveman** [comment]
> When I checked those, cal-itp.org/resources redirected me to calitp.org. 

We do want this behavior because we don't want _any_ traffic coming in on the alternate domains. It's OK if the user loses their path and has to restart, we want to encourage linkers to use the canonical domain.

**Comment by indexing** [comment]
@machikoyasuda Did you have a chance to finish this issue?

**Comment by machikoyasuda** [comment]
https://cal-itp.net
https://www.cal-itp.net

redirects set up and complete.
