### ISSUE TITLE
CSS to support converting rounded squares to rhombus

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/calitp.org#96]
This ticket is about implementing CSS that can be reused across pages to introduce the rhombus effect for Desktop screen size:

![image](https://github.com/cal-itp/calitp.org/assets/1783439/ba23a6b0-4aec-4582-b225-48cc0a70b655)

In the initial implementation of the colored box areas (across all pages), we'll focus on basic layout and getting the rounded corners correct, e.g. the Mobile screen design:

![image](https://github.com/cal-itp/calitp.org/assets/1783439/c0b6a257-29bc-4bd3-a340-5b0c2f0f9afb)

**Comment by machikoyasuda** [comment]
These also need to be refactored:

<img width="1037" alt="image" src="https://github.com/cal-itp/calitp.org/assets/3673236/f84e4985-191f-42db-b775-6821c6ec7a51">

- Remove the image bgs
- Do the mobile first
- Then write CSS later to add the diagonal lines for desktop only
