### ISSUE TITLE
Implement new design and links for Navbar

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/calitp.org#98]
The Navbar styles match that of MobiMart.

In working on this task, use placeholders (`#`) for the Resources and Press Release links so as not to be blocked by #91 and #92

**Comment by machikoyasuda** [comment]
@segacy1 Please export the Cal-ITP logo with the tightest crop possible, for both Desktop and Mobile.
<img width="361" alt="image" src="https://github.com/cal-itp/calitp.org/assets/3673236/790f6bc0-01b2-4761-b6e6-f87211811c84">
<img width="888" alt="image" src="https://github.com/cal-itp/calitp.org/assets/3673236/26338fb3-0d2a-4ba5-a23e-d17ee579bed3">


The existing site uses this, which is really hard to work with and fuzzy/not sharp.
<img width="927" alt="image" src="https://github.com/cal-itp/calitp.org/assets/3673236/c5e3aa27-bc04-4e73-b6a2-c8455b9e0302">

**Comment by segacy1** [comment]
Hey @machikoyasuda. Logos here:
![calitp-logo](https://github.com/cal-itp/calitp.org/assets/33331853/f2e7e4bf-7c68-4404-9648-f9cb50832023)
![calitp-logo](https://github.com/cal-itp/calitp.org/assets/33331853/bd40eb0c-6ed6-45fc-b36b-46fc8d601adb)

It should be the same logo for desktop/mobile!
